@echo off
echo Starting Wild Duels server...
echo Please do not close this window while playing.
echo Opening http://localhost:8000 in your browser...
start http://localhost:8000
python -m http.server 8000